# Generated by Django 4.0.3 on 2022-04-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
